# Generated by Django 5.1 on 2024-09-06 06:38

import customers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField(unique=True, validators=[customers.models.validate_unique_dob])),
                ('age', models.PositiveIntegerField()),
                ('married', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('location', models.CharField(choices=[('City', 'City'), ('Village', 'Village')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='customers/')),
            ],
        ),
    ]
